// search for airports, navaids, fixes
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const REQUEST_SEARCH_INDEX = 'REQUEST_SEARCH_INDEX';
export const RECEIVE_SEARCH_INDEX = 'RECEIVE_SEARCH_INDEX';

// geolocate a navigation item
export const LOCATE_NAV_ITEM = 'LOCATE_NAV_ITEM';
export const LOCATED_NAV_ITEM = 'LOCATED_NAV_ITEM';
export const SET_ACTIVE_NAV_ITEM = 'SET_ACTIVE_NAV_ITEM';

// geo search
export const REQUEST_GEO_SEARCH_AIRWAYS = 'REQUEST_GEO_SEARCH_AIRWAYS';
export const RECEIVE_GEO_SEARCH_AIRWAYS = 'RECEIVE_GEO_SEARCH_AIRWAYS';
export const REQUEST_GEO_SEARCH_RESULTS = 'REQUEST_GEO_SEARCH_RESULTS';
export const RECEIVE_GEO_SEARCH_RESULTS = 'RECEIVE_GEO_SEARCH_RESULTS';

// waypoints
export const CREATE_WAYPOINT = 'CREATE_WAYPOINT';
export const ADD_WAYPOINT = 'ADD_WAYPOINT';
export const REMOVE_WAYPOINT = 'REMOVE_WAYPOINT';
export const SET_WAYPOINT_INDEX = 'SET_WAYPOINT_INDEX';
export const SET_WAYPOINT_ELEVATION = 'SET_WAYPOINT_ELEVATION';
export const SET_WAYPOINT_NAV_ITEM = 'SET_WAYPOINT_NAV_ITEM';
export const SET_WAYPOINT_LAT_LON = 'SET_WAYPOINT_LAT_LON';

// flight plans
export const CREATE_FLIGHT_PLAN = 'CREATE_FLIGHT_PLAN';
export const ADD_FLIGHT_PLAN = 'ADD_FLIGHT_PLAN';
export const REMOVE_FLIGHT_PLAN = 'REMOVE_FLIGHT_PLAN';
export const SET_FLIGHT_PLAN_TITLE = 'SET_FLIGHT_PLAN_TITLE';
export const SET_FLIGHT_PLAN_COLOR = 'SET_FLIGHT_PLAN_COLOR';
export const SET_FLIGHT_PLAN_VISIBILITY = 'SET_FLIGHT_PLAN_VISIBILITY';
export const SET_FLIGHT_PLAN_AIRCRAFT = 'SET_FLIGHT_PLAN_AIRCRAFT';
export const SET_FLIGHT_PLAN_CRUISE_SPEED = 'SET_FLIGHT_PLAN_CRUISE_SPEED';
export const SET_FLIGHT_PLAN_FUEL_CONSUMPTION = 'SET_FLIGHT_PLAN_FUEL_CONSUMPTION';
export const SET_FLIGHT_PLAN_PAYLOAD = 'SET_FLIGHT_PLAN_PAYLOAD';
export const EXPORT_FLIGHT_PLAN_TO_FMS = 'EXPORT_FLIGHT_PLAN_TO_FMS';
